/**
 * Karajan Environment playbook (ENV-A1, KJC-TSK-0639).
 *
 * ONE source renders the method for every host agent: a managed block in
 * CLAUDE.md (Claude Code) and AGENTS.md (Codex). The body is data here —
 * not a template file — so it never counts as a repo AI-rule file and can
 * be parameterized later (rag/gate state, backend) without forking copies.
 *
 * The playbook is agent context: every line costs attention on every turn,
 * so it stays under 60 lines by test. Method over prose.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { upsertManagedBlock } from "../utils/managed-markers.js";

// AB-A (KJC-TSK-0650): any agent can be the brain. AGENTS.md is the
// emerging standard (Codex, Cursor and most new CLIs read it); GEMINI.md
// covers Gemini CLI. "both" is kept as a legacy alias of claude+codex.
export const PLAYBOOK_TARGETS = ["claude", "codex", "gemini", "both", "all"];

const TARGET_FILES = {
  claude: ["CLAUDE.md"],
  codex: ["AGENTS.md"],
  gemini: ["GEMINI.md"],
  both: ["CLAUDE.md", "AGENTS.md"],
  all: ["CLAUDE.md", "AGENTS.md", "GEMINI.md"],
};

// ENV-D1 (KJC-TSK-0642): the tracking invariant names the CHOSEN state
// backend — a playbook that says "board or PG" makes the host guess.
const BACKEND_TRACKING = {
  "hu-board": "Every piece of work has a tracked story/bug in the HU Board (`kj hu add` / `kj board`) before it starts — and `kj hu list` BEFORE `kj hu add`: reuse the existing card if one covers the work. Cards are permanent — never delete or recreate one; discard with `kj hu move <id> skipped`. `kj brief board` explains the board.",
  "planning-game": "Every piece of work has a tracked card in the Planning Game MCP before it starts (In Progress while you work it).",
};

// AB-C2 (KJC-TSK-0653): outcome-first — invariants over step scripts.
// Frontier models choose their own path best; what they need explicit are
// the limits. The git gates enforce these regardless of what any brain does.
const playbookBody = (stateBackend) => `# Karajan method (v4)

You are the orchestrator; Karajan governs. A task is DONE when its
done-statement is literally true, the full suite is green, and every commit
carries a cross-AI verdict.

Invariants (the git gates enforce these — they are not suggestions):

- The project RAG answers before you assume: \`kj rag query\` — never guess
  what the codebase does.
- ${BACKEND_TRACKING[stateBackend] || BACKEND_TRACKING["hu-board"]}
- Tests prove behavior: the failing test exists first (TDD), and the suite
  is never left red.
- Every diff is reviewed by a DIFFERENT AI before it is committed
  (\`kj review --staged\`): verdicts bind to the exact diff — change the code
  and it must be reviewed again. Disagree with a rejection? \`kj solomon\`.
- Security findings are never overridable — not even by arbitration. You
  absorb the security role: \`kj brief security\` states what must be true.
- Branch first: never commit on the base branch — every change reaches it
  through an atomic PR (~150 net lines, Conventional Commits). Working on
  more than one task, or the user needs the base tree untouched? One
  \`git worktree\` per task — the gates travel with the repo and work there.

Commands: \`kj rag query\` · \`kj brief <role>\` (triage, planner, researcher,
architect, tester, security, audit, board) · \`kj hu add|move|list\` · \`kj adr add|list\` ·
\`kj review --staged\` · \`kj review --check\` · \`kj solomon --position\` ·
\`kj agent run <agent>\` · \`kj report\` · \`kj check\`

Hit a kj bug or friction? Diagnose it and file it upstream with
\`kj report-issue\` (sanitized; ask your user before \`--publish\`).
`;

export function renderPlaybook({ stateBackend = "hu-board" } = {}) {
  return playbookBody(stateBackend);
}

/**
 * Install/refresh the playbook block in the target agent files.
 * User content outside the managed block is never touched.
 */
export async function installPlaybook({ projectDir, target = "all", version = "1", stateBackend = "hu-board" }) {
  if (!PLAYBOOK_TARGETS.includes(target)) {
    throw new Error(`unknown target "${target}" — use one of: ${PLAYBOOK_TARGETS.join(", ")}`);
  }
  const files = [];
  for (const file of TARGET_FILES[target]) {
    const fullPath = path.join(projectDir, file);
    let source = "";
    try { source = await fs.readFile(fullPath, "utf8"); } catch { /* new file */ }
    const { content, action } = upsertManagedBlock({
      source, blockId: "playbook", version, body: renderPlaybook({ stateBackend }), style: "html",
      note: "do not edit: regenerated by kj env install",
    });
    if (action !== "unchanged") await fs.writeFile(fullPath, content);
    files.push(file);
  }
  return { files, target };
}
