/**
 * Karajan Environment playbook (ENV-A1, KJC-TSK-0639).
 *
 * ONE source renders the method for every host agent: a managed block in
 * CLAUDE.md (Claude Code) and AGENTS.md (Codex). The body is data here —
 * not a template file — so it never counts as a repo AI-rule file and can
 * be parameterized later (rag/gate state, backend) without forking copies.
 *
 * The playbook is agent context: every line costs attention on every turn,
 * so it stays under 60 lines by test. Method over prose.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { upsertManagedBlock } from "../utils/managed-markers.js";

export const PLAYBOOK_TARGETS = ["claude", "codex", "both"];

const TARGET_FILES = { claude: ["CLAUDE.md"], codex: ["AGENTS.md"], both: ["CLAUDE.md", "AGENTS.md"] };

// ENV-D1 (KJC-TSK-0642): step 2 names the CHOSEN state backend — a playbook
// that says "board or PG" makes the host guess; the config already knows.
const BACKEND_TRACKING = {
  "hu-board": "no work without a tracked story/bug in the HU Board (`kj board`).",
  "planning-game": "no work without a tracked card in the Planning Game MCP (create it first, move it to In Progress when you start).",
};

const playbookBody = (stateBackend) => `# Karajan method (v4)

You are the orchestrator; Karajan governs the method. Follow this on every task:

1. **Context first**: before writing code, query the project RAG:
   \`kj rag query "<what you need to know>"\` — never guess what the codebase does.
2. **Card first**: ${BACKEND_TRACKING[stateBackend] || BACKEND_TRACKING["hu-board"]}
3. **TDD**: write or extend the failing test FIRST, then the code. Run the suite
   after every significant change; never leave it red.
4. **Cross-AI review before committing**: stage your changes and run
   \`kj review --staged\` — a DIFFERENT AI reviews the diff and records a verdict.
   If rejected: fix the issues and review again (the verdict is tied to the exact
   diff, so any change requires a new one). The pre-commit hook enforces this
   when the project has the review gate enabled.
5. **Security checklist** (you absorb the security role): validate all inputs,
   never commit secrets or keys, no deprecated APIs, parameterized queries,
   sanitize anything user-controlled before it reaches HTML/shell/SQL.
6. **Branch first**: never commit on the base branch — create a branch per
   task/bug and every change reaches the base only through a PR.
7. **Ship small**: Conventional Commits, atomic PRs (~150 net lines), each PR
   compiles and passes tests on its own.

Useful commands: \`kj rag query\` · \`kj review --staged\` · \`kj review --check\` ·
\`kj report\` · \`kj check\`
`;

export function renderPlaybook({ stateBackend = "hu-board" } = {}) {
  return playbookBody(stateBackend);
}

/**
 * Install/refresh the playbook block in the target agent files.
 * User content outside the managed block is never touched.
 */
export async function installPlaybook({ projectDir, target = "both", version = "1", stateBackend = "hu-board" }) {
  if (!PLAYBOOK_TARGETS.includes(target)) {
    throw new Error(`unknown target "${target}" — use one of: ${PLAYBOOK_TARGETS.join(", ")}`);
  }
  const files = [];
  for (const file of TARGET_FILES[target]) {
    const fullPath = path.join(projectDir, file);
    let source = "";
    try { source = await fs.readFile(fullPath, "utf8"); } catch { /* new file */ }
    const { content, action } = upsertManagedBlock({
      source, blockId: "playbook", version, body: renderPlaybook({ stateBackend }), style: "html",
      note: "do not edit: regenerated by kj env install",
    });
    if (action !== "unchanged") await fs.writeFile(fullPath, content);
    files.push(file);
  }
  return { files, target };
}
