/**
 * Managed-markers — idempotent file-block scaffolding for `kj harden`
 * (KJC-TSK-0555, design in docs/specs/quality-harness.md §4).
 *
 * harden owns ONLY the content between a pair of markers; everything else in
 * the file is preserved verbatim. Re-running with the same input is a no-op.
 * Generalises the `KJC-TSK-0455` marker already used by the post-merge hook
 * installer, and honours the project rule "never overwrite existing files".
 *
 * Block shape (comment syntax varies by file type):
 *   # >>> kj:managed:<id> v<N> >>> (do not edit: regenerated by kj harden)
 *   …managed body…
 *   # <<< kj:managed:<id> <<<
 */

const DEFAULT_NOTE = "do not edit: regenerated by kj harden";

/** Wrap marker payload text in the comment syntax for a given style. */
const COMMENT = {
  hash: (text) => `# ${text}`,
  slash: (text) => `// ${text}`,
  html: (text) => `<!-- ${text} -->`,
};

/** Pick a comment style from a file path. Defaults to hash (shell/yaml/conf). */
export function commentStyleFor(filePath = "") {
  if (/\.(md|markdown|mdx)$/i.test(filePath)) return "html";
  if (/\.(m?[jt]sx?|c[jt]s)$/i.test(filePath)) return "slash";
  return "hash";
}

const openPayload = (blockId, version) => `>>> kj:managed:${blockId} v${version} >>>`;
const closePayload = (blockId) => `<<< kj:managed:${blockId} <<<`;

/** Render the full managed block (open marker + body + close marker). */
export function buildManagedBlock({ blockId, version, body, style = "hash", note = DEFAULT_NOTE }) {
  const comment = COMMENT[style] ?? COMMENT.hash;
  const open = comment(`${openPayload(blockId, version)} (${note})`);
  const close = comment(closePayload(blockId));
  return `${open}\n${body}\n${close}`;
}

/**
 * Locate a managed block by id in `source`, regardless of comment style or
 * version. Returns line indices and the detected version, or { found:false }.
 */
export function findManagedBlock(source = "", blockId) {
  const lines = source.split("\n");
  const openTag = `>>> kj:managed:${blockId} v`;
  const closeTag = `<<< kj:managed:${blockId} <<<`;
  let startLine = -1;
  let version = null;
  for (let i = 0; i < lines.length; i += 1) {
    const at = lines[i].indexOf(openTag);
    if (at === -1) continue;
    const rest = lines[i].slice(at + openTag.length);
    const end = rest.indexOf(" >>>");
    const digits = end === -1 ? "" : rest.slice(0, end);
    if (/^\d+$/.test(digits)) {
      startLine = i;
      version = Number(digits);
      break;
    }
  }
  if (startLine === -1) return { found: false };
  for (let i = startLine + 1; i < lines.length; i += 1) {
    if (lines[i].includes(closeTag)) return { found: true, startLine, endLine: i, version };
  }
  return { found: false, malformed: true, startLine };
}

/**
 * Insert or update the managed block for `blockId` in `source`, preserving all
 * content outside the markers. Idempotent: identical input → action "unchanged".
 *
 * @returns {{content: string, action: "inserted"|"updated"|"unchanged", previousVersion: number|null}}
 */
export function upsertManagedBlock({ source = "", blockId, version, body, style = "hash", note }) {
  const block = buildManagedBlock({ blockId, version, body, style, note });
  const existing = findManagedBlock(source, blockId);

  if (!existing.found) {
    const base = source === "" ? "" : source.replace(/\n*$/, "\n");
    return { content: `${base}${block}\n`, action: "inserted", previousVersion: null };
  }

  const lines = source.split("\n");
  const before = lines.slice(0, existing.startLine);
  const after = lines.slice(existing.endLine + 1);
  const content = [...before, ...block.split("\n"), ...after].join("\n");
  if (content === source) return { content, action: "unchanged", previousVersion: existing.version };
  return { content, action: "updated", previousVersion: existing.version };
}
