/**
 * KJC-TSK-0891 (#1807 point 4) — what the index takes, decided without a list
 * of extensions: there are countless languages, and a list always falls short.
 * Any text file the project versions is indexable. What stays out stays out for
 * its NATURE, never its language: binary, generated, too large, excluded by the
 * project, or under a path the indexer always skips. Where a language adapter
 * exists the chunker splits by symbol; elsewhere it falls back to overlapping
 * text windows (chunkSource already does).
 */
import { execFileSync } from "node:child_process";
import { closeSync, lstatSync, openSync, readFileSync, readSync, statSync } from "node:fs";
import { join } from "node:path";

import { matchesAny } from "@karajan-family/governance";

import { buildMatchers, detectAdaptersForProject } from "../lang/registry.js";

const MAX_BYTES = 512 * 1024;
const SNIFF_BYTES = 8192;
// Generated by tools, not written by the team: noise in any language.
const GENERATED = [
  /(^|\/)(package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|Cargo\.lock|poetry\.lock|Pipfile\.lock|uv\.lock|composer\.lock|Gemfile\.lock|go\.sum)$/,
  /\.min\.(js|css)$/,
  /\.map$/,
  /\.snap$/,
];

// May hold secrets: never sent to an embedder, which can be a remote service.
const SENSITIVE = [
  /(^|\/)\.env(\.[^/]*)?$/,
  /\.(pem|key|p12|pfx|jks|keystore)$/i,
  /(^|\/)id_(rsa|dsa|ecdsa|ed25519)(\.pub)?$/,
];

// The skipped paths are the ones of THIS project's languages: Java's `bin/`
// is build output, a JS project's `bin/` is source. Cached per project.
const skipCache = new Map();
const skipsFor = (projectDir) => {
  const key = projectDir ?? "";
  if (!skipCache.has(key)) skipCache.set(key, buildMatchers(detectAdaptersForProject(projectDir ?? process.cwd())).shouldSkip);
  return skipCache.get(key);
};

/**
 * KJC-TSK-0900: `.ragignore` at the project root, gitignore syntax, versioned so
 * the whole team inherits it. `dir/` is a folder anywhere, `*.csv` an extension
 * anywhere, `/data` anchored to the root, a path with a slash is from the root.
 * `!` negation is not supported (said in the docs). Re-read when it changes.
 */
const ragignoreCache = new Map();
export function ragignoreGlobs(projectDir) {
  if (!projectDir) return [];
  const file = join(projectDir, ".ragignore");
  let mtime;
  try { mtime = statSync(file).mtimeMs; } catch { return []; }
  const hit = ragignoreCache.get(file);
  if (hit?.mtime === mtime) return hit.globs;
  const globs = [];
  for (const raw of readFileSync(file, "utf8").split("\n")) {
    let p = raw.trim();
    if (!p || p.startsWith("#") || p.startsWith("!")) continue;
    const dirOnly = p.endsWith("/");
    p = p.replace(/^\/+|\/+$/g, "");
    if (!p) continue;
    const base = raw.trim().startsWith("/") || p.includes("/") ? p : `**/${p}`;
    globs.push(`${base}/**`);
    if (!dirOnly) globs.push(base);
  }
  ragignoreCache.set(file, { mtime, globs });
  return globs;
}

/** What the project keeps out of its index: `rag.exclude`, repo-relative globs. */
export const ragExclude = (config) => (Array.isArray(config?.rag?.exclude) ? config.rag.exclude : []);

function looksBinary(abs) {
  const fd = openSync(abs, "r");
  try {
    const buf = Buffer.alloc(SNIFF_BYTES);
    const n = readSync(fd, buf, 0, SNIFF_BYTES, 0);
    return buf.subarray(0, n).includes(0);
  } finally {
    closeSync(fd);
  }
}

/**
 * @param {string} rel path relative to the project root
 * @param {string} abs absolute path
 * @param {{exclude?: string[], skip?: (rel: string) => boolean}} [opts]
 * @returns {string|null} why it stays out of the index, or null if it goes in
 */
export function indexableReason(rel, abs, { exclude = [], projectDir = null, skip = skipsFor(projectDir) } = {}) {
  if (skip(rel)) return `${rel} lives under a path the indexer always skips`;
  if (matchesAny(rel, exclude)) return `${rel} is excluded by the project's rag.exclude`;
  if (matchesAny(rel, ragignoreGlobs(projectDir))) return `${rel} is excluded by the project's .ragignore`;
  if (SENSITIVE.some((re) => re.test(rel))) return `${rel} may hold secrets, and the embedder can be a remote service`;
  if (GENERATED.some((re) => re.test(rel))) return `${rel} is a generated file (lockfile, minified, sourcemap or snapshot)`;
  let st;
  try { st = lstatSync(abs); } catch { return `${rel} does not exist`; }
  // Never followed: a versioned symlink could point the embedder at any
  // readable file outside the project, secrets included.
  if (st.isSymbolicLink()) return `${rel} is a symbolic link`;
  if (!st.isFile()) return `${rel} is not a regular file`;
  if (st.size > MAX_BYTES) return `${rel} is larger than ${MAX_BYTES / 1024} KB`;
  try {
    if (looksBinary(abs)) return `${rel} is binary`;
  } catch {
    return `${rel} could not be read`;
  }
  return null;
}

/**
 * The project's files as git sees them: versioned, plus new ones git does not
 * ignore. Null outside a git repo, so the caller can fall back to a walk.
 * @returns {string[]|null} paths relative to projectDir
 */
export function listProjectFiles(projectDir) {
  try {
    const out = execFileSync("git", ["-C", projectDir, "ls-files", "-z", "--cached", "--others", "--exclude-standard"], {
      encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], maxBuffer: 64 * 1024 * 1024,
    });
    return [...new Set(out.split("\0").filter(Boolean))];
  } catch {
    return null;
  }
}
