/**
 * Plan persistence — save, load, list plans generated by kj_plan.
 * Plans are stored at ~/.kj/plans/<projectSlug>/<planId>.json
 */

import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";

function getKjHome() {
  return process.env.KJ_HOME || path.join(os.homedir(), ".kj");
}

function projectSlug(projectDir) {
  return projectDir
    .replace(/^\//, "")
    .replace(/[/\\]/g, "_")
    .replace(/[^a-zA-Z0-9_.-]/g, "")
    .slice(0, 120);
}

function plansDir(projectDir) {
  return path.join(getKjHome(), "plans", projectSlug(projectDir));
}

function generatePlanId() {
  const now = new Date();
  const ts = now.toISOString().replace(/[-:T]/g, "").replace(/\.\d+Z$/, "");
  const rand = Math.random().toString(36).slice(2, 6);
  return `plan-${ts}-${rand}`;
}

/**
 * Save a plan result to disk.
 * @param {string} projectDir - Absolute path to the project
 * @param {object} planResult - { task, researchContext, architectContext, plan, raw }
 * @returns {Promise<string>} planId
 */
export async function savePlan(projectDir, planResult) {
  const dir = plansDir(projectDir);
  await fs.mkdir(dir, { recursive: true });

  const planId = generatePlanId();
  const record = {
    planId,
    task: planResult.task || null,
    researchContext: planResult.researchContext || null,
    architectContext: planResult.architectContext || null,
    plan: planResult.plan || null,
    raw: planResult.raw || null,
    createdAt: new Date().toISOString()
  };

  const filePath = path.join(dir, `${planId}.json`);
  await fs.writeFile(filePath, JSON.stringify(record, null, 2), "utf8");
  return planId;
}

/**
 * Load a saved plan by ID.
 * @param {string} projectDir
 * @param {string} planId
 * @returns {Promise<object|null>} { planId, task, researchContext, architectContext, plan, createdAt } or null
 */
export async function loadPlan(projectDir, planId) {
  const filePath = path.join(plansDir(projectDir), `${planId}.json`);
  try {
    const data = await fs.readFile(filePath, "utf8");
    return JSON.parse(data);
  } catch {
    return null;
  }
}

/**
 * List all plans for a project, sorted by creation time (newest first).
 * @param {string} projectDir
 * @returns {Promise<Array<{planId: string, task: string, createdAt: string}>>}
 */
export async function listPlans(projectDir) {
  const dir = plansDir(projectDir);
  let files;
  try {
    files = await fs.readdir(dir);
  } catch {
    return [];
  }

  const plans = [];
  for (const file of files) {
    if (!file.endsWith(".json")) continue;
    try {
      const data = await fs.readFile(path.join(dir, file), "utf8");
      const record = JSON.parse(data);
      plans.push({
        planId: record.planId,
        task: record.task,
        createdAt: record.createdAt
      });
    } catch { /* skip corrupt files */ }
  }

  plans.sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""));
  return plans;
}

/**
 * Get the most recent plan for a project.
 * @param {string} projectDir
 * @returns {Promise<object|null>}
 */
export async function getLatestPlan(projectDir) {
  const all = await listPlans(projectDir);
  if (all.length === 0) return null;
  return loadPlan(projectDir, all[0].planId);
}
