/**
 * KJC-TSK-0397: auto-inject a [PREFLIGHT-000] HU at the top of every
 * plan generated by `kj plan generate` so the sub-pipeline gates on a
 * clean environment before burning tokens on functional HUs.
 *
 * Design points:
 *   - Pure shell tests — no Karajan-specific runtime, just commands
 *     that exit 0 when the environment is ready.
 *   - Stack-aware: Node, Python and Firebase signals come straight
 *     from detectProjectStack() + on-disk file probes. Adding a new
 *     stack is one entry in `composePreflightTests`.
 *   - Idempotent: re-running over a plan that already has a HU with
 *     id `PREFLIGHT-000` or a title containing 'preflight' / 'verificar
 *     entorno' returns the plan unchanged. Required because the same
 *     planner output may flow through structural-pass + plan-fixer
 *     before reaching savePlan.
 *   - All other HUs' `blocked_by` get the PREFLIGHT-000 id appended
 *     (unless they already have it, again idempotent). Their own
 *     dependencies are preserved.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";

import { detectProjectStack } from "../utils/stack-detect.js";

const PREFLIGHT_ID = "PREFLIGHT-000";

/**
 * Compose stack-aware shell acceptance tests. Always includes a
 * `git status --porcelain` clean-tree check; everything else is
 * additive based on what the project actually uses.
 */
export function composePreflightTests(stack, projectDir = ".") {
  const tests = [
    { type: "shell", content: "git status --porcelain | (! grep -q .)" },
  ];
  const lang = stack?.language;
  if (lang === "javascript" || lang === "typescript") {
    tests.push({ type: "shell", content: "node --version | grep -qE '^v(2[0-9]|[3-9][0-9])'" });
    if (existsSync(join(projectDir, "package.json"))) {
      tests.push({ type: "shell", content: "npm install --no-audit --no-fund" });
      tests.push({ type: "shell", content: "test -z \"$(npm run | grep -E '^  test$')\" || npm test" });
      tests.push({ type: "shell", content: "test -z \"$(npm run | grep -E '^  lint$')\" || npm run lint" });
    }
  } else if (lang === "python") {
    tests.push({ type: "shell", content: "python --version | grep -qE 'Python 3\\.(1[0-9]|[2-9][0-9])'" });
    if (existsSync(join(projectDir, "requirements.txt"))) {
      tests.push({ type: "shell", content: "pip install -r requirements.txt" });
    } else if (existsSync(join(projectDir, "pyproject.toml"))) {
      tests.push({ type: "shell", content: "test -f poetry.lock && poetry install || pip install -e ." });
    }
    tests.push({ type: "shell", content: "command -v pytest && pytest --collect-only || true" });
  }
  if (existsSync(join(projectDir, "firebase.json"))) {
    tests.push({ type: "shell", content: "firebase projects:list" });
  }
  if (existsSync(join(projectDir, ".gcloudignore"))) {
    tests.push({ type: "shell", content: "gcloud auth list --filter=status:ACTIVE --format='value(account)' | (! test -z \"$(cat)\")" });
  }
  return tests;
}

/**
 * Return true when the plan already has a preflight-style HU (by id or
 * title). Pattern-matches conservatively to avoid duplicate injection.
 */
export function hasPreflightHu(plan) {
  if (!plan?.hus?.length) return false;
  return plan.hus.some((hu) => {
    if (hu.id === PREFLIGHT_ID) return true;
    const title = (hu.title || hu.description || "").toLowerCase();
    return title.includes("preflight-000") || title.includes("verificar entorno") || title.includes("preflight check");
  });
}

/**
 * Prepend a [PREFLIGHT-000] HU to the plan and append its id to the
 * `blocked_by` of every other HU. Returns the mutated plan reference
 * for convenience; mutation is in place so callers don't need to
 * reassign. No-op when the plan already has a preflight HU.
 */
export async function prependPreflightHu(plan, projectDir) {
  if (!plan?.hus) return plan;
  if (hasPreflightHu(plan)) return plan;
  const stack = await detectProjectStack(projectDir);
  const preflight = {
    id: PREFLIGHT_ID,
    title: "[PREFLIGHT-000] Verificar entorno de desarrollo listo",
    description: "[PREFLIGHT-000] Block functional HUs until the project's environment is reproducible: deps installed, build/test/lint passing, git tree clean, cloud auth ready when applicable.",
    task_type: "infra",
    // KJC-BUG-0108: without an explicit status, `kj plan ready` rejects the
    // whole plan with "invalid status undefined".
    status: "pending",
    blocked_by: [],
    reuse: [],
    acceptance_tests: composePreflightTests(stack, projectDir),
    spec_section: null,
  };
  for (const hu of plan.hus) {
    if (!Array.isArray(hu.blocked_by)) hu.blocked_by = [];
    if (!hu.blocked_by.includes(PREFLIGHT_ID)) hu.blocked_by.push(PREFLIGHT_ID);
  }
  plan.hus.unshift(preflight);
  return plan;
}
