import { describe, expect, it } from "vitest";

import {
  buildManagedBlock,
  commentStyleFor,
  findManagedBlock,
  upsertManagedBlock,
} from "../../src/utils/managed-markers.js";

describe("commentStyleFor", () => {
  it("maps file extensions to comment styles", () => {
    expect(commentStyleFor("CLAUDE.md")).toBe("html");
    expect(commentStyleFor("a/b.mdx")).toBe("html");
    expect(commentStyleFor("src/x.js")).toBe("slash");
    expect(commentStyleFor("src/x.mts")).toBe("slash");
    expect(commentStyleFor(".git/hooks/pre-commit")).toBe("hash");
    expect(commentStyleFor("ci.yml")).toBe("hash");
    expect(commentStyleFor("")).toBe("hash");
  });
});

describe("buildManagedBlock", () => {
  it("wraps the body in style-specific open/close markers", () => {
    const block = buildManagedBlock({ blockId: "hooks", version: 2, body: "echo hi", style: "hash" });
    expect(block).toBe(
      "# >>> kj:managed:hooks v2 >>> (do not edit: regenerated by kj harden)\n" +
        "echo hi\n" +
        "# <<< kj:managed:hooks <<<"
    );
  });

  it("uses html comments for markdown", () => {
    const block = buildManagedBlock({ blockId: "guide", version: 1, body: "rules", style: "html" });
    expect(block.startsWith("<!-- >>> kj:managed:guide v1 >>>")).toBe(true);
    expect(block.endsWith("<!-- <<< kj:managed:guide <<< -->")).toBe(true);
  });
});

describe("findManagedBlock", () => {
  it("locates a block and reports its version regardless of comment style", () => {
    const src = "header\n// >>> kj:managed:cfg v5 >>> (x)\nbody\n// <<< kj:managed:cfg <<<\nfooter";
    const found = findManagedBlock(src, "cfg");
    expect(found).toMatchObject({ found: true, startLine: 1, endLine: 3, version: 5 });
  });

  it("returns found:false when absent", () => {
    expect(findManagedBlock("nothing here", "cfg")).toEqual({ found: false });
  });

  it("flags a malformed block (open without close)", () => {
    const src = "# >>> kj:managed:cfg v1 >>>\nbody without close";
    expect(findManagedBlock(src, "cfg")).toMatchObject({ found: false, malformed: true });
  });
});

describe("upsertManagedBlock", () => {
  it("inserts at end of file preserving prior content", () => {
    const r = upsertManagedBlock({ source: "#!/bin/sh\necho keep\n", blockId: "h", version: 1, body: "echo new" });
    expect(r.action).toBe("inserted");
    expect(r.previousVersion).toBeNull();
    expect(r.content).toContain("echo keep");
    expect(r.content).toContain(">>> kj:managed:h v1 >>>");
    expect(r.content).toContain("echo new");
  });

  it("seeds an empty file without a leading blank line", () => {
    const r = upsertManagedBlock({ source: "", blockId: "h", version: 1, body: "x" });
    expect(r.content.startsWith("# >>> kj:managed:h v1 >>>")).toBe(true);
  });

  it("is idempotent: same input twice → unchanged", () => {
    const first = upsertManagedBlock({ source: "top\n", blockId: "h", version: 1, body: "x" });
    const second = upsertManagedBlock({ source: first.content, blockId: "h", version: 1, body: "x" });
    expect(second.action).toBe("unchanged");
    expect(second.content).toBe(first.content);
  });

  it("updates the managed block in place, preserving surrounding content", () => {
    const seeded = upsertManagedBlock({ source: "ABOVE\n", blockId: "h", version: 1, body: "old" }).content;
    const withTail = `${seeded}BELOW\n`;
    const updated = upsertManagedBlock({ source: withTail, blockId: "h", version: 2, body: "new" });
    expect(updated.action).toBe("updated");
    expect(updated.previousVersion).toBe(1);
    expect(updated.content).toContain("ABOVE");
    expect(updated.content).toContain("BELOW");
    expect(updated.content).toContain("v2 >>>");
    expect(updated.content).toContain("new");
    expect(updated.content).not.toContain("old");
  });

  it("only touches its own block when several coexist", () => {
    let src = upsertManagedBlock({ source: "", blockId: "a", version: 1, body: "AA" }).content;
    src = upsertManagedBlock({ source: src, blockId: "b", version: 1, body: "BB" }).content;
    const r = upsertManagedBlock({ source: src, blockId: "a", version: 2, body: "AA2" });
    expect(r.content).toContain("kj:managed:b v1");
    expect(r.content).toContain("BB");
    expect(r.content).toContain("kj:managed:a v2");
    expect(r.content).toContain("AA2");
  });
});
